### ISSUE TITLE
#error OpenNI OS Abstraction Layer - Unsupported Platform!

### ISSUE THREAD

**Issue by sebastianfoobar** [stevenlovegrove/Pangolin#112]
Hi,

I'm using Ubuntu 14.04
I'm trying to install Pangolin with the following steps: 
```
git clone https://github.com/stevenlovegrove/Pangolin.git
cd Pangolin
mkdir build
cd build
cmake -DCPP11_NO_BOOST=1 ..
make -j
```

But I get a lot of error messages like this: 

> In file included from /usr/include/ni/XnStatus.h:25:0,
                 from /usr/include/ni/XnTypes.h:28,
                 from /usr/include/ni/XnOpenNI.h:28,
                 from /usr/include/ni/XnCppWrapper.h:28,
                 from /home/USERNAME/Downloads/Pangolin/include/pangolin/video/drivers/openni.h:20,
                 from /home/USERNAME/Downloads/Pangolin/src/video/drivers/openni.cpp:28:
/usr/include/ni/XnPlatform.h:74:3: error: #error OpenNI Platform Abstraction Layer - Unsupported Platform!
  #error OpenNI Platform Abstraction Layer - Unsupported Platform!
   ^
In file included from /usr/include/ni/XnTypes.h:29:0,
                 from /usr/include/ni/XnOpenNI.h:28,
                 from /usr/include/ni/XnCppWrapper.h:28,
                 from /home/USERNAME/Downloads/Pangolin/include/pangolin/video/drivers/openni.h:20,
                 from /home/USERNAME/Downloads/Pangolin/src/video/drivers/openni.cpp:28:
/usr/include/ni/XnOS.h:52:3: error: #error OpenNI OS Abstraction Layer - Unsupported Platform!
  #error OpenNI OS Abstraction Layer - Unsupported Platform!
   ^

I also found the other issue with this but it didn't help, when I execute:
`cmake -DCPP11_NO_BOOST=1 ..`

I get also this as an output 
```
-- OpenNI Found and Enabled
-- OpenNI2 Found and Enabled
```
So OpenNI is installed. 

But on make -j I get the errors from above. I have now no more idea what to do. If you need additional infos please ask.

Thanks

**Comment by stevenlovegrove** [comment]
I think this has been fixed in the devel branch. The problem only exists in the OpenNI1 code, so you can either try the devel branch or tell Pangolin not to find OpenNI1. I'd recommend using OpenNI2 anyway since it is actively maintained in Pangolin.

**Comment by sebastianfoobar** [comment]
Thanks, it helped a bit.
Now I'm using OpenNI2, but now I get a similar error. 

> In file included from /usr/include/openni2/OpenNI.h:24:0,
                 from /home/sebastian/Downloads/Pangolin/include/pangolin/video/drivers/openni2.h:37,
                 from /home/sebastian/Downloads/Pangolin/src/video/drivers/openni2.cpp:29:
/usr/include/openni2/OniPlatform.h:49:3: error: #error Xiron Platform Abstraction Layer - Unsupported Platform!
 # error Xiron Platform Abstraction Layer - Unsupported Platform!
   ^
In file included from /usr/include/openni2/OpenNI.h:24:0,
                 from /home/sebastian/Downloads/Pangolin/include/pangolin/video/drivers/openni2.h:37,
                 from /home/sebastian/Downloads/Pangolin/src/video/video.cpp:48:
/usr/include/openni2/OniPlatform.h:49:3: error: #error Xiron Platform Abstraction Layer - Unsupported Platform!
 # error Xiron Platform Abstraction Layer - Unsupported Platform!

**Comment by stevenlovegrove** [comment]
Could you try adding the definition -D__linux__=1 to this line
https://github.com/stevenlovegrove/Pangolin/blob/devel/src/CMakeLists.txt#L303

You need to make sure this test succeeds...
https://github.com/occipital/OpenNI2/blob/master/Include/OniPlatform.h#L40

If it works for you, I will patch Pangolin to include the change.

**Comment by sebastianfoobar** [comment]
I tried it with your change on the devel branch. 
But I still get the same error. 

May it be a problem that I installed OpenNi2 with the package manager? 
`sudo apt-get install openni2-utils openni2-doc`
I don't know how I could verify that the test succeeds.

**Comment by stevenlovegrove** [comment]
In that case you'll need to look in the header on your own machine and try to work out what is triggering the error. It will be testing some define that you should try pushing in to Pangolin via compiler flags as suggested above. You could also use 
VERBOSE=1 make

When building Pangolin to check that the flag is being passed for the openni2.cpp compilation unit.

**Comment by skic** [comment]
I also get the same problem.Can you show more details about how to tell Pangolin not to find OpenNI1

**Comment by skic** [comment]
when I delete the find_package(OpenNI) .It is  Ok

**Comment by stevenlovegrove** [comment]
If you want Pangolin to ignore a library, just set it's lib and include directories to the empty string in ccmake or cmake-gui. This will cause find_package to fail and Pangolin to proceed without it without any code changes.
