### ISSUE TITLE
system crash with command "make -j"

### ISSUE THREAD

**Issue by DamonMIN** [stevenlovegrove/Pangolin#99]
When I install Pangolin in my ubuntu system, the system crashed with the command "make -j". I have tried many times, this problem appeared again and again. I don't know why. Can you help me to solve it?

**Comment by stevenlovegrove** [comment]
Can you be more specific? What do you mean by install? What is the exact output? What happens if you omit the -j option? If make itself is segfaulting, you probably have bigger problems than Pangolin's source code! You could try launching make through GBD for clues...

**Comment by DamonMIN** [comment]
The crash has been solved.Thank u for your write back.
The problem is that Pangolin needs more virtual memory building the source code. Re-allocating more virtual memory for computer is the right way.

**Comment by stevenlovegrove** [comment]
Glad you solved your issue.

**Comment by Santi-7** [comment]
How many virtual memory did u need? I have the same problem, in a virtual machine with Ubuntu.

**Comment by lothas** [comment]
I have the same issue: make -j crashes ubuntu 16.04.
The system just completely freezes.

**Comment by arifle** [comment]
@stevenlovegrove 
Hi, Steven. It seems that I got the same problem which happens at 83% of the whole compilation (of course, it stopped there). I modified the VM configuration to increase it to 5GB. I still failed ... 
I have no idea now because my physical memory is only 4 GB. I don't know how much bigger is required? BTW, 83% is fonts.c.o ...

**Comment by stevenlovegrove** [comment]
I'm not sure - it's possible that embedding the font file is causing your compiler to allocate a lot of memory for some reason. You could try replacing the font file with a much smaller file as a test to see if that really is the cause. You could also try a different compiler (e.g. clang / gcc 5).

**Comment by arifle** [comment]
I made attempts with 4.7 4.9 and 5 none of them works.
